### ISSUE TITLE
Add arrow on horizontal carousels

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#14]
Please can we add an arrow on the right hand side of the window to every horizontal scrolling carousel that we use on the site please. 

[arrow.svg.zip](https://github.com/saiminh/shynthesis-wptheme/files/7170254/arrow.svg.zip)

<img width="840" alt="Screenshot 2021-09-15 at 15 02 54" src="https://user-images.githubusercontent.com/18393982/133438268-c2fa7ccf-46fa-49ff-a69a-3bc117c9132f.png">

<img width="697" alt="Screenshot 2021-09-15 at 15 03 34" src="https://user-images.githubusercontent.com/18393982/133438360-8b1d7ae7-e4f0-46c2-b844-423e2d0d5701.png">

**Comment by saiminh** [comment]
Not ideal the arrow is hidden by the images quite frequently...

**Comment by jackmez** [comment]
Hi Simon, 
is it possible to add functionality to the arrow? so if the user clicks the arrow it moves them through forward and backwards one card. 

To do this can we add an additional arrow on the left hand side and update the design to make it stand out more.
<img width="926" alt="Screenshot 2021-09-21 at 07 35 58" src="https://user-images.githubusercontent.com/18393982/134123240-021f7ced-da85-4f8c-8456-80583199f99b.png">
