### ISSUE TITLE
Home page links

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#18]
I added links to the buttons on the homepage but I can't work out how to make sure the text remains blue in the CMS?

<img width="373" alt="Screenshot 2021-09-15 at 23 35 25" src="https://user-images.githubusercontent.com/18393982/133512924-1c9d986d-bb90-474a-bc91-f431178f0cdd.png">

**Comment by jackmez** [comment]
The buttons are correct when on a white background but wrong when on a blue background…

**Comment by saiminh** [comment]
This is fixed, the link had the color white assigned in WordPress.
