### ISSUE TITLE
Update design of cookie banner on mobile 

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#19]
new design:
<img width="767" alt="Screenshot 2021-09-15 at 23 39 48" src="https://user-images.githubusercontent.com/18393982/133513378-2a61f93a-833b-4515-b07f-1783c36f6f3c.png">

Please make sure the blue gradient doesn't start until the end of the cookie banner text, currently the two display on top of each other: 
<img width="439" alt="Screenshot 2021-09-15 at 23 41 30" src="https://user-images.githubusercontent.com/18393982/133513605-50be4bfd-b09d-40f7-b8eb-caeaa367730b.png">

**Comment by jackmez** [comment]
Please note the client is looking at using https://www.iubenda.com/en/ for their cookie policy

**Comment by saiminh** [comment]
> Please note the client is looking at using https://www.iubenda.com/en/ for their cookie policy

This just refers to the textual content of the policy I assume?
I have spent time integrating a cookie policy solution on the site manually, so if this is also a technical solution, I will have to get rid of my solution and replace it with this one, and amend the CSS...
