### ISSUE TITLE
Update site text alignment

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#2]
Don't set paragraph indentations on the main headlines, lets just apply it on the smaller paragraph boxes.
Home page ok as it is.

<img width="381" alt="Screenshot 2021-09-08 at 17 03 42" src="https://user-images.githubusercontent.com/18393982/132534809-da03540a-9139-47a4-b514-5082741c1531.png">

<img width="413" alt="Screenshot 2021-09-08 at 17 03 46" src="https://user-images.githubusercontent.com/18393982/132534790-9a5af9e2-8c80-4636-bedb-0a79f2a4254e.png">

<img width="395" alt="Screenshot 2021-09-08 at 17 03 39" src="https://user-images.githubusercontent.com/18393982/132534814-b7be3e65-c1c9-4371-8230-ba5385cc802d.png">

**Comment by saiminh** [comment]
This is done

**Comment by jackmez** [comment]
The secondary paragraphs should still have some paragraph indentation

Current live site:
<img width="1194" alt="Screenshot 2021-09-08 at 17 32 53" src="https://user-images.githubusercontent.com/18393982/132539774-a8883c5e-443d-48fc-a737-f558fa835030.png">

Design intent:
<img width="681" alt="Screenshot 2021-09-08 at 17 33 52" src="https://user-images.githubusercontent.com/18393982/132539855-8f0b0eb6-e5fc-47e7-9701-f550a7e1f9e3.png">

**Comment by jackmez** [comment]
The first paragraph after a h1 headline 👍
