### ISSUE TITLE
Link newsletter signup to mailchimp 

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#20]
I don't have the account credentials yet but adding it here so we don't forget.

**Comment by jackmez** [comment]
When a user submits their email, is it possible to add a confirmation message such as "Thank you for signing up"?

**Comment by saiminh** [comment]
> When a user submits their email, is it possible to add a confirmation message such as "Thank you for signing up"?

I think this is usually already a feature of mailchimp's embedded forms. We'll have to see how customizable it is, but this would most likely be done from the mailchimp dashboard.
If not I'm not sure how we can get a callback for a successfull submit, since this happens on mailchimp servers. To build a custom form from scratch that interacts with mailchimp API is not in scope for this launch I'm afraid.

**Comment by jackmez** [comment]
Hi Simon, 
Rosie has the details for Mailchimp now.

I filled in the embedded form details, can we build our form from the following code?

`
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://capital.us5.list-manage.com/subscribe/post?u=932baccf9539a469160cbfc7f&amp;id=e85e5f5d38" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name </label>
	<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name </label>
	<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_932baccf9539a469160cbfc7f_e85e5f5d38" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
`

**Comment by saiminh** [comment]
Hi Jack,
Did you delete the code from your comment? I think from what I can see in the version history of your comment, you pasted some stuff before... 
If you're pasting embed code to me here, remember to use the 'Insert code' formatting, otherwise github will likely strip all html tags and such things from the comment...

**Comment by jackmez** [comment]
Ahh sorry simon it kept formatting it differently. 

This this work?

[synth mailchimp form.html.zip](https://github.com/saiminh/shynthesis-wptheme/files/7244983/synth.mailchimp.form.html.zip)

**Comment by saiminh** [comment]
Seems to work

**Comment by jackmez** [comment]
Hey Simon please could we increase the size of the confirmation text for the form and center it to the page?

**Comment by saiminh** [comment]
Done
