### ISSUE TITLE
Add footer content to CMS

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#22]
Is the content in the footer available in the CMS. 
(I can't work out how to update the address in the footer)

**Comment by saiminh** [comment]
No footer content is static. Please provide the changes you want and I can amend

**Comment by jackmez** [comment]
Is there a way to expose this in the CMS? 

The client is moving address in a few weeks but doesn't know where to yet… it would be good for them to be able to update this (as well as add the social links themselves)

**Comment by saiminh** [comment]
Discussed with Pat to not do this for launch. The theme file where this lives is footer.php, but remember to update on github and then pull instead of changing directly on server.

**Comment by saiminh** [comment]
I’ve done it for you now.

Clicking ‘Update Theme’ in WPPusher basically is just a ‘git pull’ in the theme folder.
You could also SSH into the folder directly with ’ssh ***@***.***’, go to the theme folder and then ‘git pull’ from there. Both do the same thing. 

Usually WPPusher can be set to automatically pull all changes as soon the repo changes, but GoDaddy is blocking that somehow it seems. (In WPPusher it says ‘push-to-deploy active’ but it seems to be a lie)

Cheers,
Simon

**Comment by jackmez** [comment]
Thank you Simon, good to know!
