### ISSUE TITLE
Add page signpost to last section of Focus page

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#3]
Tried to do this in the CMS but current alignment wont let me align with the rest of the page.

<img width="972" alt="Screenshot 2021-09-08 at 17 07 43" src="https://user-images.githubusercontent.com/18393982/132535452-00f4920b-7107-4319-b074-9c7db6fe6d20.png">

**Comment by saiminh** [comment]
“Add page signpost to last section of Focus page” can you explain? I don’t quite understand what that means

**Comment by jackmez** [comment]
I added it in the CMS here:

"how do we do it"  but can we update the design to keep it locked up to the left hand side of the page?

<img width="636" alt="Screenshot 2021-09-08 at 18 07 58" src="https://user-images.githubusercontent.com/18393982/132545208-9739ef90-5104-4774-9b26-22bf75471784.png">
