### ISSUE TITLE
Alternate Stylistic Set by Default

### ISSUE THREAD

**Issue by patrickforpeople** [saiminh/shynthesis-wptheme#31]
![image](https://user-images.githubusercontent.com/18527541/134002398-252c8992-93c8-449e-9a1d-7c0e5cc4e646.png)
^Current

Should default to stylstic set of ligatures 01, so that dots on i's & j's are polygonal, not rectangular 
vDesired
![image](https://user-images.githubusercontent.com/18527541/134002510-53bdda15-1779-4232-ad19-bc240f5f549c.png)

**Comment by saiminh** [comment]
Actually doing some research, stylistic sets are not supported by any browser other than Firefox and Safari at the moment (https://caniuse.com/font-variant-alternates), so minority will actually see it.
Also in case you still want it, I need the full proper name of the stylistic set as a string. (font-variant-alternates: stylistic(stylistic-1) isn't working so I guess the name is wrong...)

**Comment by jackmez** [comment]
`font-feature-settings: 'ss01'; `

**Comment by saiminh** [comment]
Thanks! This is done now
