### ISSUE TITLE
Font Defaults

### ISSUE THREAD

**Issue by patrickforpeople** [saiminh/shynthesis-wptheme#39]
Hey Simon, I think we talked about making sure the stylistic alternates on the font were switched to alternative 1 by default (so that the i and j have polygons instead of rectangles as their 'dots')

**Comment by saiminh** [comment]
It is turned on by default. However I checked and it appears Chrome doesn't respect the styling when it's set directly to the @font-face element, so I applied it now to the individual DOM elements as well as a fix and should now also render in Chrome.
