### ISSUE TITLE
Chrome Windows — Home Page line

### ISSUE THREAD

**Issue by patrickforpeople** [saiminh/shynthesis-wptheme#40]
![image](https://user-images.githubusercontent.com/18527541/134654473-2c7b7f2d-a142-446f-ba64-7c587a357488.png)

anything dirty we can do to make sure this line doesn't appear at base of gradient?

**Comment by saiminh** [comment]
I'm testing it on Chrome v91 on Windows 10 and can't replicate this whatever I try. 
Could you please clear cache, (I'll clear server side cache too again just to be sure) and tell me the Versions of OS and Chrome, the Screen resolution and Browser Viewport-width (if applies, or if it applies on all viewport sizes) and what exactly you did (if anything) before seeing the bug? (Like resized window or scrolled down before loading complete or stuff like that)

**Comment by patrickforpeople** [comment]
ah, this appears resolved now! not sure what it was
