### ISSUE TITLE
Cookie Policy 

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#44]
Hi Simon, 

Please we can update the cookie policy to use the Iubenda account set up by Synthesis? 

The details are
email:
rosie@synthesis.capital

pw:
Synth_Cap_21!

Can we link from the banner already implemented?

**Comment by saiminh** [comment]
Could you explain a bit more what you mean by this? I’m not sure what lubenda does or what services it provides. I have already created a cookie policy feature and tested it with Google Analytics, so what are you expecting this to do differently or better? Is it just about the text of the cookie policy? That can just be copy pasted into a WordPress page no?

**Comment by saiminh** [comment]
Original cookie policy implemented
