### ISSUE TITLE
Team page Bios spacing issue 

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#45]
I am unable to replicate this issue on my ipad or using the mobile emulator via the inspector but Rosie is seeing the team bios like this on iPad:

Any ideas?

![IMG-0065](https://user-images.githubusercontent.com/18393982/135311669-d9537b8d-ecf2-45bb-87b7-35e12c0c4e55.PNG)
![IMG-0064](https://user-images.githubusercontent.com/18393982/135311697-d76d4933-4f7e-4d49-b25f-a8ea07f96dec.PNG)

**Comment by saiminh** [comment]
Ah yeah, likely an old Safari version that doesn't support the gap property... I switched the layout to an older margin based syntax which should work on older iPads that haven't been updated.
