### ISSUE TITLE
Margin on second row of team page. 

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#49]
Hey Simon,
Please can we align the second row of the team bios to the left.
(should start in the same place as the first row)
Thank you

![image (16)](https://user-images.githubusercontent.com/18393982/135443159-a31f4198-d810-4a02-b09a-f061f8979a25.png)

**Comment by saiminh** [comment]
shit this happened bcs of that old safari bug change. also now done
