### ISSUE TITLE
Remove ligature from first paragraph of the Investment page.

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#5]
The 'Ca' in 'CPT Capital' should not be joined.

Should look like:
<img width="762" alt="Screenshot 2021-09-08 at 17 11 52" src="https://user-images.githubusercontent.com/18393982/132536122-e9d30de4-70ce-452b-976a-0b83c02d4cfc.png">

**Comment by saiminh** [comment]
Done with update
