### ISSUE TITLE
Update layout of founder quotes on 'Investments' page 

### ISSUE THREAD

**Issue by jackmez** [saiminh/shynthesis-wptheme#8]
Can we add one column space between each quote, increase the vertical space between each quote and offset every other row of quotes by a column.  

<img width="700" alt="Screenshot 2021-09-08 at 17 31 33" src="https://user-images.githubusercontent.com/18393982/132539456-60bb06d7-7389-41d7-ae9f-cfb626ad4e2c.png">

**Comment by jackmez** [comment]
Profile Image should be much smaller

<img width="616" alt="Screenshot 2021-09-08 at 18 03 35" src="https://user-images.githubusercontent.com/18393982/132544458-6ff51c6d-9a2d-4483-b33f-07acf4f25174.png">

**Comment by jackmez** [comment]
White border should only span the width of the quote

**Comment by jackmez** [comment]
Second row should not align with the start of the second quote of the first row

**Comment by saiminh** [comment]
I think you need to clear your cache...

**Comment by jackmez** [comment]
correct! 👍

**Comment by jackmez** [comment]
Profile images still need to reduce in size by about 50px

**Comment by saiminh** [comment]
Reduced size by what equals to 50px on desktop screens...
